Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,6 +32,6 @@ jobs:
       run: mysql -h ${{ secrets.DB_HOSTNAME }} --port 3306 -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "SHOW DATABASES";
     - name: Run a sample SQL on remote
       run: mysql -h ${{ secrets.DB_HOSTNAME }} --port 3306 -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "source hawthorn/hawthorn_script.sql";
-    - name:  Failing  code
-      if:  ${{inputs.fail-on == 'dv'}}
-      run: exit 1
+  #  - name:  Failing  code
+   #   if:  ${{inputs.fail-on == 'dv'}}
+    #  run: exit 1
